# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6823179842a1b1c53905d87d0c4f1695"
application_url = "https://digital-anumati-banner-app.onrender.com"
embedded = true
name = "Digital Anumati Consent Banner"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]



[auth]
redirect_urls = [ "https://digital-anumati-banner-app.onrender.com/api/auth" ]


[build]
automatically_update_urls_on_dev = true

